spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/webdb
        username: webuser
        password: admin123!
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
#                show_sql: true
            default_batch_fetch_size: 1000    # 100??? ?? 1000? ??
        database-platform: org.hibernate.dialect.MariaDB103Dialect
logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

logging:
  level:
    org.springframework: DEBUG